### ISSUE TITLE
Hello the bot gives me this error

### ISSUE THREAD

**Issue by MrRay70915** [MattBSG/ModTools#7]
Hello, I went through the windows installer and then when it was done to start.bat and it gave me this error https://gyazo.com/1c27b98da49c15b353c741bbdeffc9c8

**Comment by MattBSG** [comment]
Hi, can you do me a favor and rerun windows-installer.bat and confirm your config settings are correct?

**Comment by MattBSG** [comment]
No response from issue poster

**Comment by LoganDark** [comment]
That's because a newer version (not sure which version specifically) of the library uses `int`s for snowflakes instead of `string`s. Wrap `self.user.id` in a call to `str()` and you'll be fine.

@MattBSG the config has nothing to do with this. I don't mean to be rude, but can you even read a traceback?

**Comment by MattBSG** [comment]
Yes, I am able to read a traceback. I was (until now) unaware of that library change and I was not able to reproduce at the time. I’ve only seen TypeErrors in the past associated with user misconfiguration. This project is also only maintained at this point in time, and the original bot was written a very long time ago by SexualRhinoceros.

**Comment by MattBSG** [comment]
Thank you for informing me of the library change. That’s what I get for assuming user error.

**Comment by LoganDark** [comment]
You shouldn't be "assuming" anything. The problem and cause of the problem is right there in the traceback. Config has nothing to do with it.
